Fix cg-admin-setuprepo warning on missing post-update hook
cg-admin-setuprepo would always show the 'see the NOTES section'
message, while it should do so only in the case the post-update hook is
missing. While at it, smoothen up the warning a bit.

diff --git a/cg-admin-setuprepo b/cg-admin-setuprepo
--- a/cg-admin-setuprepo
+++ b/cg-admin-setuprepo
@@ -80,6 +80,7 @@ fi
 git-init-db
 
 # Enable git-update-server-info after each push.
-chmod a+x "$_git/hooks/post-update" ||
-	echo "Due to this file missing, HTTP pull will not work properly on this repository." >&2 &&
-	echo "See the NOTES section of cg-admin-setuprepo(1)'s documentation." >&2
+if ! chmod a+x "$_git/hooks/post-update"; then
+	echo "Due to the missing post-update hook, HTTP pull will not work properly on this repository." >&2
+	echo "See the NOTES section of cg-admin-setuprepo(1)'s documentation for more details." >&2
+fi
