Simplify seek detection
Don't dig information from .git/blocked, just look if .git/HEAD is a
symlink and get the branch information from $_git_branch.

diff --git a/cg-cancel b/cg-cancel
--- a/cg-cancel
+++ b/cg-cancel
@@ -22,15 +22,13 @@ if ! [ -s $_git/HEAD ]; then
 fi
 
 # Undo seek?
-branch=
-[ -s $_git/blocked ] && branch=$(sed -n 's/^seeked from //p' < $_git/blocked)
-if [ "$branch" ]; then
-	echo "Unseeking: $(cat $_git/HEAD) -> $(cat "$_git/refs/heads/$branch")"
-	if [ -s "$_git/refs/heads/$branch" ]; then
+if [ ! "$(readlink $_git/HEAD)" ]; then
+	echo "Unseeking: $(cat $_git/HEAD) -> $(cat "$_git/refs/heads/$_git_branch")"
+	if [ -s "$_git/refs/heads/$_git_branch" ]; then
 		rm $_git/HEAD
-		ln -s "refs/heads/$branch" $_git/HEAD
+		ln -s "refs/heads/$_git_branch" $_git/HEAD
 	else
-		echo "ERROR: Unknown branch $branch! Preserving HEAD." >&2
+		echo "ERROR: Unknown branch $_git_branch! Preserving HEAD." >&2
 	fi
 fi
 
