Move merge state files from .git/ to .git/cg-merge-state/
so that they do not pollute the .git/ directory itself but are safely
caged. You should not upgrade Cogito in the middle of merge, though.

diff --git a/cg-commit b/cg-commit
--- a/cg-commit
+++ b/cg-commit
@@ -325,6 +325,9 @@ if [ -s "$_git/blocked" ] && [ ! "$writeref" ]; then
 		die "committing blocked: $(cat "$_git/blocked")"
 	fi
 fi
+# Deprecated as of 2006-11-17
+[ -s "$_git/merging" ] && die "old-style merge state detected, panicking; you upgraded cogito in the middle of a merge! redo the merge, cg-reset will bring you back to the starting line"
+mstatedir="$_git/cg-merge-state"
 
 if [ ! "$ignorecache" ]; then
 	cg-object-id HEAD >/dev/null 2>&1 || ignorecache=1
@@ -357,7 +360,7 @@ fi
 
 if [ "$ARGS" -o "$_git_relpath" ]; then
 	[ "$ignorecache" ] && die "you cannot list files for the initial commit"
-	[ -s "$_git/merging" ] && die "cannot commit individual files when merging"
+	[ -s "$mstatedir/merging" ] && die "cannot commit individual files when merging"
 
 	filter="$tmpdir/filter"
 	[ "$_git_relpath" -a ! "$ARGS" ] && echo "$_git_relpath" >>"$filter"
@@ -386,10 +389,10 @@ else
 		eval "commitfiles=($(git-diff-index --name-status -z -r -m HEAD | \
 			perl -n0e 'chomp; if (defined $meta) { s/([\"\\])/\\\1/; print "\"$meta $_\"\n"; $meta=undef } else { $meta = $_ }'))"
 
-		if [ -s "$_git/commit-ignore" ]; then
+		if [ -s "$mstatedir/commit-ignore" ]; then
 			newcommitfiles=()
 			for file in "${commitfiles[@]}"; do
-				fgrep -qx "${file:2}" "$_git/commit-ignore" && continue
+				fgrep -qx "${file:2}" "$mstatedir/commit-ignore" && continue
 				newcommitfiles[${#newcommitfiles[@]}]="$file"
 			done
 			commitfiles=("${newcommitfiles[@]}")
@@ -399,7 +402,7 @@ else
 	[ "$review" ] && git-diff-index -r -m -p HEAD > "$PATCH"
 
 	merging=
-	[ -s "$_git/merging" ] && merging="$(cat "$_git/merging" | sed 's/^/-p /')"
+	[ -s "$mstatedir/merging" ] && merging="$(cat "$mstatedir/merging" | sed 's/^/-p /')"
 fi
 
 
@@ -416,18 +419,18 @@ if [ "$merging" ] && [ ! "$editor" ]; then
 	warn "suppressing default merge log messages in favour of the custom -m passed to me."
 elif [ "$merging" ]; then
 	echo -n 'Merge with ' >>"$LOGMSG"
-	[ -s "$_git/merging-sym" ] || cp "$_git/merging" "$_git/merging-sym"
-	for sym in $(cat "$_git/merging-sym"); do
+	[ -s "$mstatedir/merging-sym" ] || cp "$mstatedir/merging" "$mstatedir/merging-sym"
+	for sym in $(cat "$mstatedir/merging-sym"); do
 		uri="$(cat "$_git/branches/$sym" 2>/dev/null)"
 		[ "$uri" ] || uri="$sym"
 		echo "$uri" >>"$LOGMSG"
 	done
 	echo >>"$LOGMSG"
-	if [ -s "$_git/squashing" ]; then
+	if [ -s "$mstatedir/squashing" ]; then
 		# We are squashing all the merged commits to a single one.
 		# Therefore, helpfully pre-fill the commit message with
 		# the messages of all the merged commits.
-		git-rev-list --pretty "$(cat "$_git/merging")" ^HEAD >>"$LOGMSG"
+		git-rev-list --pretty "$(cat "$mstatedir/merging")" ^HEAD >>"$LOGMSG"
 	fi
 	written=1
 fi
@@ -499,9 +502,9 @@ if [ ! "$ignorecache" ] && [ ! "$review" ]; then
 		echo "CG:F   $file" >>"$LOGMSG"
 		[ ! "$editor" ] && echo "$file"
 	done
-	if [ -s "$_git/commit-ignore" ]; then
+	if [ -s "$mstatedir/commit-ignore" ]; then
 		echo "CG:" >>"$LOGMSG"
-		echo "CG: I have kept back the $(wc -l "$_git/commit-ignore" | cut -d ' ' -f 1) file(s) containing your local changes." >>"$LOGMSG"
+		echo "CG: I have kept back the $(wc -l "$mstatedir/commit-ignore" | cut -d ' ' -f 1) file(s) containing your local changes." >>"$LOGMSG"
 		echo "CG: You need not worry, the local changes will not interfere with the merge." >>"$LOGMSG"
 	fi
 fi
@@ -538,7 +541,7 @@ if editor_shalluse "$forceeditor"; then
 			cat >&2 <<__END__
 Note that the merge is NOT aborted - you can cg-commit again, cg-reset will abort it.
 __END__
-			[ -s "$_git/commit-ignore" ] && cat >&2 <<__END__
+			[ -s "$mstatedir/commit-ignore" ] && cat >&2 <<__END__
 (But note that cg-reset will remove your pending local changes as well!)
 __END__
 		fi
@@ -638,7 +641,7 @@ if [ ! "$force" ] && [ ! "$merging" ] && [ "$oldhead" ] &&
 	exit 2;
 fi
 
-[ -s "$_git/squashing" ] && merging=" " # viciously prevent recording a proper merge
+[ -s "$mstatedir/squashing" ] && merging=" " # viciously prevent recording a proper merge
 newhead=$(git-commit-tree $treeid $oldheadstr $merging <"$LOGMSG")
 rm "$LOGMSG"
 
@@ -655,8 +658,7 @@ commit_over()
 
 commit_cleanup()
 {
-	[ "$merging" ] && rm -f "$_git/merging" "$_git/merging-sym" "$_git/merge-base" "$_git/squashing"
-	rm -f "$_git/commit-ignore"
+	rm -rf "$mstatedir"
 }
 
 if [ "$push" ]; then
diff --git a/cg-merge b/cg-merge
--- a/cg-merge
+++ b/cg-merge
@@ -173,8 +173,12 @@ fi
 
 
 [ -s "$_git/blocked" ] && die "merge blocked: $(cat "$_git/blocked")"
+# Deprecated as of 2006-11-17
+[ -s "$_git/merging" ] && die "old-style merge state detected, panicking; you upgraded cogito in the middle of a merge! redo the merge, cg-reset will bring you back to the starting line"
 
-if [ -s "$_git/merging" ] && grep -q "$branch" "$_git/merging"; then
+statedir="$_git/cg-merge-state"
+
+if [ -s "$statedir/merging" ] && grep -q "$branch" "$statedir/merging"; then
 	echo "Branch already merged in the working tree." >&2
 	exit 0
 fi
@@ -184,7 +188,7 @@ if [ "$base" = "$branch" ]; then
 	exit 0
 fi
 
-if { [ "$head" = "$base" ] || [ "$head" = "$_cg_orig_head" ]; } && [ ! "$squash" ] && [ ! -s "$_git/merging" ]; then
+if { [ "$head" = "$base" ] || [ "$head" = "$_cg_orig_head" ]; } && [ ! "$squash" ] && [ ! -s "$statedir/merging" ]; then
 	# No need to do explicit merge with a merge commit; just bring
 	# the HEAD forward.
 
@@ -204,7 +208,7 @@ fi
 git-update-index --refresh >/dev/null
 
 if [ ! "$squash" ]; then
-	[ -s "$_git/squashing" ] && die "cannot combine squashing and non-squashing merges"
+	[ -s "$statedir/squashing" ] && die "cannot combine squashing and non-squashing merges"
 
 	echo "Merging $base -> $branch" >&2
 	echo -e "\tto $head ..." >&2
@@ -221,21 +225,24 @@ fi
 
 prehook "$mergetype"
 
-git-diff-index --name-only "$(cg-object-id -t $head)" >>"$_git/commit-ignore"
+mkdir -p "$statedir"
+
+git-diff-index --name-only "$(cg-object-id -t $head)" >>"$statedir/commit-ignore"
 # Don't keep around useless empty files
-[ -s "$_git/commit-ignore" ] || rm "$_git/commit-ignore"
+[ -s "$statedir/commit-ignore" ] || rm "$statedir/commit-ignore"
 
 if ! git-read-tree -u -m "$(cg-object-id -t "$base")" "$(cg-object-id -t "$head")" "$(cg-object-id -t "$branch")"; then
 	echo "cg-merge: git-read-tree failed (merge likely blocked by local changes)" >&2
 	posthook "$mergetype" localchanges
-	rm -f "$_git/commit-ignore"
+	rm -f "$statedir/commit-ignore"
+	rmdir "$statedir"
 	exit 1
 fi
 
-echo "$base" >>"$_git/merge-base"
-echo "$branch" >>"$_git/merging"
-echo "$branchname" >>"$_git/merging-sym"
-[ "$squash" ] && echo "$branch" >>"$_git/squashing"
+echo "$base" >>"$statedir/merge-base"
+echo "$branch" >>"$statedir/merging"
+echo "$branchname" >>"$statedir/merging-sym"
+[ "$squash" ] && echo "$branch" >>"$statedir/squashing"
 
 if ! git-merge-index -o -q "${COGITO_LIB}"cg-Xmergefile -a || [ "$careful" ]; then
 	echo >&2
@@ -244,11 +251,11 @@ if ! git-merge-index -o -q "${COGITO_LIB}"cg-Xmergefile -a || [ "$careful" ]; th
 	else
 		echo "	Do cg-commit after reviewing the merge." >&2
 	fi
-	if [ -s "$_git/commit-ignore" ]; then
+	if [ -s "$statedir/commit-ignore" ]; then
 		echo "	cg-reset will cancel the merge (but also your pending local changes!)." >&2
 		echo >&2
 		echo "	These files contained local modifications and won't be automatically chosen for committing:" >&2
-		cat "$_git/commit-ignore" >&2
+		cat "$statedir/commit-ignore" >&2
 	else
 		echo "	cg-reset will cancel the merge." >&2
 		echo >&2
@@ -262,7 +269,7 @@ readtree=
 if ! cg-commit -C; then
 	readtree=1
 	echo "cg-merge: COMMIT FAILED, retry manually" >&2
-	if [ -s "$_git/commit-ignore" ]; then
+	if [ -s "$statedir/commit-ignore" ]; then
 		echo "	cg-reset will cancel the merge (but also your pending local changes!)." >&2
 	else
 		echo "	cg-reset will cancel the merge." >&2
