Remove cloning functionality from cg-init
All the cloning is now done in cg-clone, therefore cg-init no longer
takes the location argument (which was deprecated for long anyway).

diff --git a/cg-clone b/cg-clone
--- a/cg-clone
+++ b/cg-clone
@@ -58,10 +58,16 @@ else
 	dir=.
 fi
 
-trap ":" SIGINT SIGTERM
-if ! cg-init $location; then
-	ret=$?
-	cd .. && rmdir $dir
-	exit $ret
-fi
+
+trap "cd .. && rm -rf $dir; echo; die \"interrupted\"" SIGINT SIGTERM
+
+cg-init -I
+cg-branch-add origin "$location"
+cg-pull origin || die "pull failed"
+
+cp $_git/refs/heads/origin $_git/refs/heads/master
+git-read-tree HEAD
+git-checkout-cache -a
+git-update-cache --refresh
+
 echo "Cloned to $dir/ (origin $location available as branch \"origin\")"
