Whitespaces safety fixes
Fix hopefully all the possible whitespace and metacharacters related
problems by carefully quoting everything.  Even most of the things clearly
unneeded, because it doesn't harm and I want to cultivate a reflex to panic
and closely investigate if anything unquoted passes by, so that we _stay_
safe in the future as well.

Such a large patch is bound to introduce some (probably mostly trivial) bugs,
so please test this carefully.

diff --git a/cg-commit b/cg-commit
--- a/cg-commit
+++ b/cg-commit
@@ -129,20 +129,20 @@ USAGE="cg-commit [-m MESSAGE]... [-C] [-e | -E] [-s | --signoff] [-c COMMIT_ID] 
 . ${COGITO_LIB}cg-Xlib || exit 1
 
 
-[ -s $_git/blocked ] && die "committing blocked: $(cat $_git/blocked)"
+[ -s "$_git/blocked" ] && die "committing blocked: $(cat "$_git/blocked")"
 
-if [ -s $_git/author ]; then
-	if [ -z "$GIT_AUTHOR_NAME" ] && grep -q '^[^<]' $_git/author; then
-		export GIT_AUTHOR_NAME="$(sed 's/ *<.*//' $_git/author)"
+if [ -s "$_git/author" ]; then
+	if [ -z "$GIT_AUTHOR_NAME" ] && grep -q '^[^<]' "$_git/author"; then
+		export GIT_AUTHOR_NAME="$(sed 's/ *<.*//' "$_git/author")"
 	fi
-	if [ -z "$GIT_AUTHOR_EMAIL" ] && grep -q '<.*>' $_git/author; then
-		export GIT_AUTHOR_EMAIL="$(sed 's/.*<\(.*\)>.*/\1/' $_git/author)"
+	if [ -z "$GIT_AUTHOR_EMAIL" ] && grep -q '<.*>' "$_git/author"; then
+		export GIT_AUTHOR_EMAIL="$(sed 's/.*<\(.*\)>.*/\1/' "$_git/author")"
 	fi
 fi
 if [ -z "$GIT_AUTHOR_NAME" -o -z "$GIT_AUTHOR_EMAIL" ]; then
 	# Always pre-fill those so that the user can modify them in the
 	# commit template.
-	idline=$(git-var GIT_AUTHOR_IDENT)
+	idline="$(git-var GIT_AUTHOR_IDENT)"
 	[ -z "$GIT_AUTHOR_NAME" ] && export GIT_AUTHOR_NAME="$(echo "$idline" | sed 's/ *<.*//')"
 	[ -z "$GIT_AUTHOR_EMAIL" ] && export GIT_AUTHOR_EMAIL="$(echo "$idline" | sed 's/.*<\(.*\)>.*/\1/')"
 fi
@@ -189,19 +189,19 @@ done
 
 if [ "$ARGS" -o "$_git_relpath" ]; then
 	[ "$ignorecache" ] && die "-C and listing files to commit does not make sense"
-	[ -s $_git/merging ] && die "cannot commit individual files when merging"
+	[ -s "$_git/merging" ] && die "cannot commit individual files when merging"
 
-	filter=$(mktemp -t gitci.XXXXXX)
-	[ "$_git_relpath" -a ! "$ARGS" ] && echo "$_git_relpath" >>$filter
+	filter="$(mktemp -t gitci.XXXXXX)"
+	[ "$_git_relpath" -a ! "$ARGS" ] && echo "$_git_relpath" >>"$filter"
 	for file in "${ARGS[@]}"; do
-		echo "${_git_relpath}$file" >>$filter
+		echo "${_git_relpath}$file" >>"$filter"
 	done
 
-	eval "commitfiles=($(cat $filter | path_xargs git-diff-index -r -m HEAD -- | \
+	eval "commitfiles=($(cat "$filter" | path_xargs git-diff-index -r -m HEAD -- | \
 		sed 's/^\([^	]*\)\(.	.*\)\(	.*\)*$/"\2"/'))"
 	customfiles=1
 
-	rm $filter
+	rm "$filter"
 
 else
 	# We bother with added/removed files here instead of updating
@@ -228,30 +228,30 @@ else
 	fi
 
 	merging=
-	[ -s $_git/merging ] && merging=$(cat $_git/merging | sed 's/^/-p /')
+	[ -s "$_git/merging" ] && merging="$(cat "$_git/merging" | sed 's/^/-p /')"
 fi
 
 
-LOGMSG=$(mktemp -t gitci.XXXXXX)
-LOGMSG2=$(mktemp -t gitci.XXXXXX)
+LOGMSG="$(mktemp -t gitci.XXXXXX)"
+LOGMSG2="$(mktemp -t gitci.XXXXXX)"
 
 written=
 if [ "$merging" ] && [ "$msgs" ] && [ ! "$forceeditor" ]; then
 	echo "Warning: Suppressing default merge log messages in favour of the custom -m passed to me." >&2
 elif [ "$merging" ]; then
-	echo -n 'Merge with ' >>$LOGMSG
-	[ -s $_git/merging-sym ] || cp $_git/merging $_git/merging-sym
-	for sym in $(cat $_git/merging-sym); do
-		uri=$(cat $_git/branches/$sym 2>/dev/null)
+	echo -n 'Merge with ' >>"$LOGMSG"
+	[ -s "$_git/merging-sym" ] || cp "$_git/merging" "$_git/merging-sym"
+	for sym in $(cat "$_git/merging-sym"); do
+		uri="$(cat "$_git/branches/$sym" 2>/dev/null)"
 		[ "$uri" ] || uri="$sym"
-		echo "$uri" >>$LOGMSG
+		echo "$uri" >>"$LOGMSG"
 	done
-	echo >>$LOGMSG
+	echo >>"$LOGMSG"
 	if [ -s "$_git/squashing" ]; then
 		# We are squashing all the merged commits to a single one.
 		# Therefore, helpfully pre-fill the commit message with
 		# the messages of all the merged commits.
-		git-rev-list --pretty $(cat "$_git/merging") ^HEAD >>$LOGMSG
+		git-rev-list --pretty "$(cat "$_git/merging")" ^HEAD >>"$LOGMSG"
 		read
 	fi
 	written=1
@@ -261,9 +261,9 @@ for msg in "${msgs[@]}"; do
 	if [ "$first" ]; then
 		first=
 	else
-		echo >>$LOGMSG
+		echo >>"$LOGMSG"
 	fi
-	echo "$msg" | fmt -s >>$LOGMSG
+	echo "$msg" | fmt -s >>"$LOGMSG"
 	written=1
 done
 
@@ -296,11 +296,11 @@ if [ "$copy_commit" ]; then
 	export GIT_AUTHOR_DATE
 	git-cat-file commit "$copy_commit" | sed -e '1,/^$/d'
         written=1
-fi >> $LOGMSG
+fi >>"$LOGMSG"
 
 # Always have at least one blank line, to ease the editing for
 # the poor people whose text editor has no 'O' command.
-[ "$written" ] || echo >>$LOGMSG
+[ "$written" ] || echo >>"$LOGMSG"
 
 if [ "$signoff" ] && ! grep -q -i "signed-off-by: $signoff" $LOGMSG; then
 	grep -q -i sign-off-by $LOGMSG || echo
@@ -308,58 +308,58 @@ if [ "$signoff" ] && ! grep -q -i "signed-off-by: $signoff" $LOGMSG; then
 fi >> $LOGMSG
 
 if [ -e "$_git/commit-template" ]; then
-	cat $_git/commit-template >>$LOGMSG
+	cat "$_git/commit-template" >>"$LOGMSG"
 else
-	cat >>$LOGMSG <<EOT
+	cat >>"$LOGMSG" <<EOT
 CG: -----------------------------------------------------------------------
 CG: Lines beginning with the CG: prefix are removed automatically.
 EOT
 fi
 if [ "$GIT_AUTHOR_NAME" -o "$GIT_AUTHOR_EMAIL" -o "$GIT_AUTHOR_DATE" ]; then
-	echo "CG:" >>$LOGMSG
-	[ "$GIT_AUTHOR_NAME" ] && echo "CG: Author: $GIT_AUTHOR_NAME" >>$LOGMSG
-	[ "$GIT_AUTHOR_EMAIL" ] && echo "CG: Email: $GIT_AUTHOR_EMAIL" >>$LOGMSG
-	[ "$GIT_AUTHOR_DATE" ] && echo "CG: Date: $GIT_AUTHOR_DATE" >>$LOGMSG
-	echo "CG:" >>$LOGMSG
+	echo "CG:" >>"$LOGMSG"
+	[ "$GIT_AUTHOR_NAME" ] && echo "CG: Author: $GIT_AUTHOR_NAME" >>"$LOGMSG"
+	[ "$GIT_AUTHOR_EMAIL" ] && echo "CG: Email: $GIT_AUTHOR_EMAIL" >>"$LOGMSG"
+	[ "$GIT_AUTHOR_DATE" ] && echo "CG: Date: $GIT_AUTHOR_DATE" >>"$LOGMSG"
+	echo "CG:" >>"$LOGMSG"
 fi
 
 if [ ! "$ignorecache" ]; then
 	if [ ! "$merging" ]; then
 		if [ ! "$force" ] && [ ! "${commitfiles[*]}" ]; then
-			rm $LOGMSG $LOGMSG2
+			rm "$LOGMSG" "$LOGMSG2"
 			[ "$quiet" ] && exit 0 || die 'Nothing to commit'
 		fi
-		echo "CG: By deleting lines beginning with CG:F, the associated file" >>$LOGMSG
-		echo "CG: will be removed from the commit list." >>$LOGMSG
+		echo "CG: By deleting lines beginning with CG:F, the associated file" >>"$LOGMSG"
+		echo "CG: will be removed from the commit list." >>"$LOGMSG"
 	fi	
-	echo "CG:" >>$LOGMSG
-	echo "CG: Modified files:" >>$LOGMSG
+	echo "CG:" >>"$LOGMSG"
+	echo "CG: Modified files:" >>"$LOGMSG"
 	for file in "${commitfiles[@]}"; do
 		# TODO: Prepend a letter describing whether it's addition,
 		# removal or update. Or call git status on those files.
-		echo "CG:F   $file" >>$LOGMSG
-		[ "$msgs" ] && ! [ "$forceeditor" ] && echo $file
+		echo "CG:F   $file" >>"$LOGMSG"
+		[ "$msgs" ] && ! [ "$forceeditor" ] && echo "$file"
 	done
 	if [ -s "$_git/commit-ignore" ]; then
-		echo "CG:" >>$LOGMSG
-		echo "CG: I have kept back the $(wc -l "$_git/commit-ignore" | cut -d ' ' -f 1) file(s) containing your local changes." >>$LOGMSG
-		echo "CG: You need not worry, the local changes will not interfere with the merge." >>$LOGMSG
+		echo "CG:" >>"$LOGMSG"
+		echo "CG: I have kept back the $(wc -l "$_git/commit-ignore" | cut -d ' ' -f 1) file(s) containing your local changes." >>"$LOGMSG"
+		echo "CG: You need not worry, the local changes will not interfere with the merge." >>"$LOGMSG"
 	fi
 fi
-[ "$commitalways" ] || echo "CG: Do not save this file and just quit if you want to abort the commit." >>$LOGMSG
-echo "CG: -----------------------------------------------------------------------" >>$LOGMSG
-echo "CG: vim: textwidth=75" >>$LOGMSG
+[ "$commitalways" ] || echo "CG: Do not save this file and just quit if you want to abort the commit." >>"$LOGMSG"
+echo "CG: -----------------------------------------------------------------------" >>"$LOGMSG"
+echo "CG: vim: textwidth=75" >>"$LOGMSG"
 
-cp $LOGMSG $LOGMSG2
+cp "$LOGMSG" "$LOGMSG2"
 if tty -s; then
 	if ! ([ "$copy_commit" ] || [ "$msgs" ]) || [ "$forceeditor" ]; then
-		${EDITOR:-vi} $LOGMSG2
-		if ! [ "$commitalways" ] && ! [ $LOGMSG2 -nt $LOGMSG ]; then
+		${EDITOR:-vi} "$LOGMSG2"
+		if ! [ "$commitalways" ] && ! [ "$LOGMSG2" -nt "$LOGMSG" ]; then
 			echo "Log message unchanged or not specified" >&2
 			while true; do
 				read -p 'Abort or commit? [ac] ' choice
 				if [ "$choice" = "a" ] || [ "$choice" = "q" ]; then
-					rm $LOGMSG $LOGMSG2
+					rm "$LOGMSG" "$LOGMSG2"
 					echo "Commit message not modified, commit aborted" >&2
 					if [ "$merging" ]; then
 						cat >&2 <<__END__
@@ -377,9 +377,9 @@ __END__
 		fi
 	fi
 	if [ ! "$ignorecache" ] && [ ! "$merging" ]; then
-		eval "newcommitfiles=($(grep ^CG:F $LOGMSG2 | sed 's/^CG:F *\(.*\)$/"\1"/'))"
+		eval "newcommitfiles=($(grep ^CG:F "$LOGMSG2" | sed 's/^CG:F *\(.*\)$/"\1"/'))"
 		if [ ! "$force" ] && [ ! "${newcommitfiles[*]}" ]; then
-			rm $LOGMSG $LOGMSG2
+			rm "$LOGMSG" "$LOGMSG2"
 			[ "$quiet" ] && exit 0 || die 'Nothing to commit'
 		fi
 		if [ "${commitfiles[*]}" != "${newcommitfiles[*]}" ]; then
@@ -388,29 +388,29 @@ __END__
 		fi
 	fi
 	setif () {
-		if ! grep -q "^CG: $2:" $LOGMSG2; then
+		if ! grep -q "^CG: $2:" "$LOGMSG2"; then
 			unset $1
 		else
-			export $1="$(grep "^CG: $2:" $LOGMSG2 |cut -d ' ' -f 3-)"
+			export $1="$(grep "^CG: $2:" "$LOGMSG2" | cut -d ' ' -f 3-)"
 		fi
 	}
 	setif GIT_AUTHOR_NAME Author
 	setif GIT_AUTHOR_EMAIL Email
 	setif GIT_AUTHOR_DATE Date
 else
-	cat >$LOGMSG2
+	cat >"$LOGMSG2"
 fi
 # Remove heading and trailing blank lines.
-grep -v ^CG: $LOGMSG2 | git-stripspace >$LOGMSG
-rm $LOGMSG2
+grep -v ^CG: "$LOGMSG2" | git-stripspace >"$LOGMSG"
+rm "$LOGMSG2"
 
 
 precommit_update()
 {
 	queueN=(); queueD=(); queueM=();
 	for file in "$@"; do
-		op=${file%%[ 	]*}
-		fname=${file#*[ 	]}
+		op="${file%%[ 	]*}"
+		fname="${file#*[ 	]}"
 		[ "$op" = "N" ] && op=A # N is to be renamed to A
 		[ "$op" = "A" ] || [ "$op" = "D" ] || [ "$op" = "M" ] || op=M
 		eval "queue$op[\${#queue$op[@]}]=\"\$fname\""
@@ -428,7 +428,7 @@ precommit_update()
 if [ ! "$ignorecache" ]; then
 	if [ "$customfiles" ]; then
 		precommit_update "${commitfiles[@]}" || die "update-cache failed"
-		export GIT_INDEX_FILE=$(mktemp -t gitci.XXXXXX)
+		export GIT_INDEX_FILE="$(mktemp -t gitci.XXXXXX)"
 		git-read-tree HEAD
 	fi
 	precommit_update "${commitfiles[@]}" || die "update-cache failed"
@@ -442,7 +442,7 @@ if [ -s "$_git/$oldheadname" ]; then
 	oldheadstr="-p $oldhead"
 fi
 
-treeid=$(git-write-tree ${missingok})
+treeid="$(git-write-tree ${missingok})"
 [ "$treeid" ] || die "git-write-tree failed"
 if [ ! "$force" ] && [ ! "$merging" ] && [ "$oldhead" ] &&
    [ "$treeid" = "$(cg-object-id -t)" ]; then
@@ -453,33 +453,33 @@ if [ ! "$force" ] && [ ! "$merging" ] && [ "$oldhead" ] &&
 fi
 
 [ -s "$_git/squashing" ] && merging=" " # viciously prevent recording a proper merge
-newhead=$(git-commit-tree $treeid $oldheadstr $merging <$LOGMSG)
-rm $LOGMSG
+newhead=$(git-commit-tree $treeid $oldheadstr $merging <"$LOGMSG")
+rm "$LOGMSG"
 
 if [ "$customfiles" ]; then
-	rm $GIT_INDEX_FILE
+	rm "$GIT_INDEX_FILE"
 	export GIT_INDEX_FILE=
 fi
 
 if [ "$newhead" ]; then
 	git-update-ref HEAD $newhead $oldhead || die "unable to move to the new commit $newhead"
 	echo "Committed as $newhead."
-	[ "$merging" ] && rm -f $_git/merging $_git/merging-sym $_git/merge-base $_git/squashing
+	[ "$merging" ] && rm -f "$_git/merging" "$_git/merging-sym" "$_git/merge-base" "$_git/squashing"
 	rm -f "$_git/commit-ignore"
 
 	# Trigger the postcommit hook
 	branchname=
-	if [ -s $_git/branch-name ]; then
+	if [ -s "$_git/branch-name" ]; then
 		echo "Warning: .git/branch-name is deprecated and support for it will be removed soon." >&2
 		echo "Warning: So please stop relying on it, or complain at pasky@suse.cz. Thanks." >&2
-		branchname=$(cat $_git/branch-name)
+		branchname="$(cat "$_git/branch-name")"
 	fi
 	[ -z "$branchname" ] && [ "$_git_head" != "master" ] && branchname="$_git_head"
-	if [ -x $_git/hooks/commit-post ]; then
+	if [ -x "$_git/hooks/commit-post" ]; then
 		# We just hope that for the initial commit, the user didn't
 		# manage to install the hook yet.
 		for merged in $(git-rev-list $newhead ^$oldhead | tac); do
-			$_git/hooks/commit-post $merged $branchname
+			"$_git/hooks/commit-post" "$merged" "$branchname"
 		done
 	fi
 
diff --git a/cg-export b/cg-export
--- a/cg-export
+++ b/cg-export
@@ -30,36 +30,36 @@ if [ -z "$id" ]; then
 	id="$(cg-object-id -c)"
 fi
 
-dest=${ARGS[0]}
+dest="${ARGS[0]}"
 
 ([ -n "$dest" ] && [ -n "$id" ]) || usage
 
 [ -e "$dest" ] && die "$dest already exists."
 
-case $dest in
+case "$dest" in
 	*.tar|*.tar.gz|*.tar.bz2|*.tgz)
-		base=${dest%.tar*}
-		base=${base%.tgz}
-		ext=${dest#$base}
-		base=${base##*/}
-		case $ext in
+		base="${dest%.tar*}"
+		base="${base%.tgz}"
+		ext="${dest#$base}"
+		base="${base##*/}"
+		case "$ext" in
 		.tar.gz|.tgz)
-			git-tar-tree $id "$base" | gzip -c9 $tar > $dest
+			git-tar-tree "$id" "$base" | gzip -c9 "$tar" >"$dest"
 			;;
 		.tar.bz2)
-			git-tar-tree $id "$base" | bzip2 -c $tar > $dest
+			git-tar-tree "$id" "$base" | bzip2 -c "$tar" >"$dest"
 			;;
 		.tar)
-			git-tar-tree $id "$base" > $dest
+			git-tar-tree "$id" "$base" >"$dest"
 			;;
 		esac
 		;;
 	*)
-		mkdir -p $dest || die "cannot create $dest"
+		mkdir -p "$dest" || die "cannot create $dest"
 		export GIT_INDEX_FILE="$dest/.git-index"
 		id="$(cg-object-id -t "$id")"
-		git-read-tree $id
+		git-read-tree "$id"
 		git-checkout-index "--prefix=$dest/" -a
-		rm $GIT_INDEX_FILE
+		rm "$GIT_INDEX_FILE"
 	;;
 esac
