[PATCH Cogito] Use git-{update,symbolic}-ref for updating HEAD
Conditionally make git-update-ref check the old head. For this to succeed
for the initial commit, cg-init should not touch .git/refs/heads/master,
and the touching seems to be redundant anyway, so remove it.

This should make Cogito mostly work on cygwin.

Signed-off-by: Jonas Fonseca <fonseca@diku.dk>

Fixed few bugs and hopefully made complete.

Signed-off-by: Petr Baudis <pasky@suse.cz>

diff --git a/cg-commit b/cg-commit
--- a/cg-commit
+++ b/cg-commit
@@ -417,8 +417,9 @@ fi
 
 
 oldhead=
-if [ -s "$_git/HEAD" ]; then
-	oldhead=$(cat $_git/HEAD)
+oldheadname="$(git-symbolic-ref HEAD)"
+if [ -s "$_git/$oldheadname" ]; then
+	oldhead="$(cat "$_git/$oldheadname")"
 	oldheadstr="-p $oldhead"
 fi
 
@@ -442,8 +443,8 @@ if [ "$customfiles" ]; then
 fi
 
 if [ "$newhead" ]; then
+	git-update-ref HEAD $newhead $oldhead || die "unable to move to the new commit $newhead"
 	echo "Committed as $newhead."
-	echo $newhead >$_git/HEAD
 	[ "$merging" ] && rm -f $_git/merging $_git/merging-sym $_git/merge-base $_git/squashing
 	rm -f "$_git/commit-ignore"
 
