Move tags fetching to fetch_tags() subroutine

diff --git a/cg-fetch b/cg-fetch
--- a/cg-fetch
+++ b/cg-fetch
@@ -180,6 +180,41 @@ fetch_local()
 }
 
 
+fetch_tags()
+{
+	# FIXME: Warn about conflicting tag names?
+	[ -d "$_git/refs/tags" ] || mkdir -p "$_git/refs/tags"
+
+	if [ "$get" = "get_rsync" ]; then
+		$get -i -s -u -d "$uri/refs/tags" "$_git/refs/tags" ||
+			echo "unable to get tags list (non-fatal)" >&2
+		exit $?
+	fi
+
+	git-ls-remote --tags "$uri" |
+		# SHA1 refs/tags/v0.99.8^{} --> SHA1 tags/v0.99.8
+		# where SHA1 is the object v0.99.8 tag points at.
+		sed -ne 's:\([^	]\)	refs/\(tags/.*\)^{}$:\1 \2:p' |
+		while read sha1 tagname; do
+			# Do we have the tag itself?
+			[ -s "$_git/refs/$tagname" ] && continue
+			# Do we have the object pointed at by the tag?
+			git-cat-file -t "$sha1" >/dev/null 2>&1 || continue
+
+			# if so, fetch the tag -- which should be
+			# a cheap operation -- to complete the chain.
+			echo -n "Missing tag ${tagname#tags/}... "
+			if $fetch "$tagname" "$uri" "$tagname" 2>/dev/null >&2; then
+				echo "retrieved"
+			else
+				echo "unable to retrieve"
+			fi
+		done
+	[ "${PIPESTATUS[0]}" -eq "0" ] ||
+		echo "unable to get tags list (non-fatal)" >&2
+}
+
+
 recovery=
 verbose=
 while optparse; do
@@ -299,38 +334,7 @@ else
 fi
 rm "$_git/refs/heads/.$name-fetching"
 
-
-### Fetch tags
-# FIXME: Warn about conflicting tag names?
-[ -d "$_git/refs/tags" ] || mkdir -p "$_git/refs/tags"
-
-if [ "$get" = "get_rsync" ]; then
-	$get -i -s -u -d "$uri/refs/tags" "$_git/refs/tags" ||
-		echo "unable to get tags list (non-fatal)" >&2
-else
-	git-ls-remote --tags "$uri" |
-		# SHA1 refs/tags/v0.99.8^{} --> SHA1 tags/v0.99.8
-		# where SHA1 is the object v0.99.8 tag points at.
-		sed -ne 's:\([^	]\)	refs/\(tags/.*\)^{}$:\1 \2:p' |
-		while read sha1 tagname; do
-			# Do we have the tag itself?
-			[ -s "$_git/refs/$tagname" ] && continue
-			# Do we have the object pointed at by the tag?
-			git-cat-file -t "$sha1" >/dev/null 2>&1 || continue
-
-			# if so, fetch the tag -- which should be
-			# a cheap operation -- to complete the chain.
-			echo -n "Missing tag ${tagname#tags/}... "
-			if $fetch "$tagname" "$uri" "$tagname" 2>/dev/null >&2; then
-				echo "retrieved"
-			else
-				echo "unable to retrieve"
-			fi
-		done
-	[ "${PIPESTATUS[0]}" -eq "0" ] ||
-		echo "unable to get tags list (non-fatal)" >&2
-fi
-
+fetch_tags
 
 rm "$_git/info/cg-fetch-$name-dirty"
 
