Do not use .*-fetching tmp heads during checking
Seriously, the kind of stuff we were vomiting there does not have any
place in the refs/ tree at all. Just use a normal temporary file for
it instead.

diff --git a/cg-fetch b/cg-fetch
--- a/cg-fetch
+++ b/cg-fetch
@@ -146,7 +146,7 @@ fetch_rsync_verify()
 				done ||
 			die "rsync fetch incomplete, some objects missing"
 		fi
-		git-update-ref "refs/$3" "$(get_ref "refs/${3%/*}/.${3##*/}-fetching")"
+		git-update-ref "refs/$3" "$1"
 	fi
 	return $ret
 }
@@ -391,30 +391,29 @@ fi
 
 ### Behold, the fetch itself
 
-# Here we play it a bit (a lot) dirty and do not use the ref accessors for
-# the temporary fetching ref - it is not required (it's never gonna be
-# packed and we don't need the atomicity) and it makes the code a lot simpler.
-# We would only have a problem if someone did git-pack-refs --all in the middle
-# of a fetch, and that ought to never happen. Right? Right.
-
 ## Grab the head
 echo "Fetching head..."
-mkdir -p "$_git/refs/heads/$(dirname "$name")"
-tmpname="$(dirname "$name")/.$(basename "$name")-fetching"
+
+tmpname="$(mktemp -t githead.XXXXXX)"
+cleanup () {
+	rm "$tmpname"
+}
+cleanup_trap "cleanup"
+
 if [ "$rembranch" ]; then
-	$get -i "$uri/refs/heads/$rembranch" "$_git/refs/heads/$tmpname" ||
+	$get -i "$uri/refs/heads/$rembranch" "$tmpname" ||
 		die "unable to get the head pointer of branch $rembranch"
 else
-	$get -b "$uri/HEAD" "$_git/refs/heads/$tmpname" ||
+	$get -b "$uri/HEAD" "$tmpname" ||
 		die "unable to get the HEAD branch"
 fi
 
-new_head="$(cat "$_git/refs/heads/$tmpname")"
+new_head="$(cat "$tmpname")"
 if [ "${new_head#ref:}" != "$new_head" ]; then
 	new_head="$(echo "$new_head" | sed 's/^ref: *//')"
-	$get -i "$uri/$new_head" "$_git/refs/heads/$tmpname" ||
+	$get -i "$uri/$new_head" "$tmpname" ||
 		die "unable to get the head pointer of branch $new_head (referenced by HEAD)"
-	new_head="$(cat "$_git/refs/heads/$tmpname")"
+	new_head="$(cat "$tmpname")"
 fi
 
 rm -f "$_git/info/cg-fetch-earlydie"
@@ -424,12 +423,14 @@ echo "Fetching objects..."
 if ! [ "$symlinked" ]; then
 	if [ "$recovery" -o "$orig_head" != "$new_head" ]; then
 		[ -d "$_git_objects" ] || mkdir -p "$_git_objects"
-		$fetch "$(cat "$_git/refs/heads/$tmpname")" "$uri" "heads/$name" || die "objects fetch failed"
+		$fetch "$(cat "$tmpname")" "$uri" "heads/$name" || die "objects fetch failed"
 	fi
 else
-	git-update-ref "refs/heads/$name" "$(cat "$_git/refs/heads/$tmpname")"
+	git-update-ref "refs/heads/$name" "$(cat "$tmpname")"
 fi
-rm "$_git/refs/heads/$tmpname"
+
+rm "$tmpname"
+cleanup_trap ""
 
 ## Fetch the tags
 ret=0
