Support for cg-mkpatch -d
cg-mkpatch -d DIRNAME will output the patches splitted to individual
files into the given directory.

diff --git a/cg-mkpatch b/cg-mkpatch
--- a/cg-mkpatch
+++ b/cg-mkpatch
@@ -7,9 +7,16 @@
 #
 # OPTIONS
 # -------
-# -s::
-#	Specify whether to print a short version of the patch without
-#	a patch header with meta info such as author and committer.
+# -d DIRNAME::
+#	Split the patches to separate files with their names in the
+#	format "%02d.patch", created in directory DIRNAME (will be
+#	created if non-existant). Note that this makes sense only
+#	when generating patch series, that is when you use the -r
+#	argument.
+#
+# -m::
+#	Base the patches at the merge base of the -r arguments
+#	(defaulting to HEAD and origin).
 #
 # -r FROM_ID[:TO_ID]::
 #	Specify a set of commits to make patches from using either
@@ -19,9 +26,9 @@
 #	from 'FROM_ID' to the initial commit will be generated. If no
 #	`-r` option is given the commit ID defaults to 'HEAD'.
 #
-# -m::
-#	Base the patches at the merge base of the -r arguments
-#	(defaulting to HEAD and origin).
+# -s::
+#	Specify whether to print a short version of the patch without
+#	a patch header with meta info such as author and committer.
 #
 # EXAMPLE USAGE
 # -------------
@@ -30,12 +37,12 @@
 #
 #	$ cg-mkpatch -r releasetag-0.9:releasetag-0.10
 #
-# The output will be a contionuos dump of patches each separated by
+# The output will be a continuous dump of patches each separated by
 # the line:
 #
 #	!-------------------------------------------------------------flip-
 
-USAGE="cg-mkpatch [-m] [-s] [-r FROM_ID[:TO_ID]]"
+USAGE="cg-mkpatch [-m] [-s] [-r FROM_ID[:TO_ID] [-d DIRNAME]]"
 _git_requires_root=1
 
 . ${COGITO_LIB}cg-Xlib || exit 1
@@ -81,7 +88,7 @@ omit_header=
 log_start=
 log_end=
 mergebase=
-
+outdir=
 while optparse; do
 	if optparse -s; then
 		omit_header=1
@@ -101,6 +108,8 @@ while optparse; do
 		fi
 	elif optparse -m; then
 		mergebase=1
+	elif optparse -d=; then
+		outdir="$OPTARG"
 	else
 		optfail
 	fi
@@ -118,17 +127,30 @@ if [ "$log_end" ]; then
 	id1=$(commit-id "$log_start") || exit 1
 	id2=$(commit-id "$log_end") || exit 1
 
+	if [ "$outdir" ]; then
+		mkdir -p "$outdir" || die "cannot create patch directory"
+		pnum=001
+	fi
+
 	git-rev-list --merge-order $id2 ^$id1 | tac | while read id; do
-		showpatch $id
-		echo
-		echo
-		echo -e '\014'
-		echo '!-------------------------------------------------------------flip-'
-		echo
-		echo
+		if [ "$outdir" ]; then
+			filename="$(printf "%s/%03d.patch" "$outdir" "$pnum")"
+			echo "$filename"
+			showpatch $id >"$filename"
+			pnum=$((pnum+1))
+		else
+			showpatch $id
+			echo
+			echo
+			echo -e '\014'
+			echo '!-------------------------------------------------------------flip-'
+			echo
+			echo
+		fi
 	done
 
 else
+	[ "$outdir" ] && die "-d makes sense only for patch series"
 	id=$(commit-id "$log_start") || exit 1
 	showpatch $id
 fi
