cg-merge -j for joining disjoint branches
Sometimes you want to join two projects together, and that's where
cg-merge -j hurries to help. It will work _only_ in that case and without
it, cg-merge will refuse to do anything, so it works like some kind of
'yes, I really want to do it in this case', since sometimes it may be
just a plain user error.

Inspired by Alan Chandler.

diff --git a/cg-merge b/cg-merge
--- a/cg-merge
+++ b/cg-merge
@@ -44,6 +44,14 @@
 #	basically make cg-merge always behave like there were conflicts
 #	during the merge.
 #
+# -j::
+#	Join the current branch and BRANCH_NAME together. This makes sense
+#	when the branches have no common history, meaning they are actually
+#	not branches related at all as far as GIT is concerned. Merging such
+#	branches might be a user error and you well may be doing something
+#	you do not want; but equally likely, you may actually WANT to join
+#	the projects together, which is what this option does.
+#
 # FILES
 # -----
 # $GIT_DIR/hooks/merge-pre::
@@ -62,7 +70,7 @@
 #	STATUS is always "ok", while for "tree" the STATUS can be
 #	"localchanges", "conflicts", "nocommit", or "ok".
 
-USAGE="cg-merge [-c] [-b BASE_COMMIT] [BRANCH_NAME]"
+USAGE="cg-merge [-c] [-b BASE_COMMIT] [-j] [BRANCH_NAME]"
 _git_requires_root=1
 
 . ${COGITO_LIB}cg-Xlib || exit 1
@@ -88,11 +96,14 @@ head=$(cg-object-id -c) || exit 1
 
 careful=
 base=
+join=
 while optparse; do
 	if optparse -c; then
 		careful=1
 	elif optparse -b=; then
 		base=$(cg-object-id -c "$OPTARG") || exit 1
+	elif optparse -j; then
+		join=1
 	else
 		optfail
 	fi
@@ -104,7 +115,15 @@ branchname="${ARGS[0]}"
 branch=$(cg-object-id -c "$branchname") || exit 1
 
 [ "$base" ] || base=$(git-merge-base "$head" "$branch")
-[ "$base" ] || die "unable to automatically determine merge base"
+if [ ! "$join" ]; then
+	[ "$base" ] || die "unable to automatically determine merge base (consider cg-merge -j)"
+else
+	[ "$base" ] && die "joining branches with common history is something I refuse to do"
+	index="$(mktemp -t gitmerge.XXXXXX)" || exit $?
+	GIT_INDEX_FILE="$index" git-read-tree
+	base=$(GIT_INDEX_FILE="$index" git-write-tree)
+	rm "$index"
+fi
 
 
 [ -s $_git/blocked ] && die "merge blocked: $(cat $_git/blocked)"
