Make cg-restore list the files being restored
Before, it did that only for the en masse restore - change its format
and use it for the per-file restoring as well.

diff --git a/cg-restore b/cg-restore
--- a/cg-restore
+++ b/cg-restore
@@ -84,10 +84,11 @@ if [ "$ARGS" ]; then
 		if ! git-ls-tree -r "$objid" "${files[@]}" |
 			sed -ne 's/^\([0-7]*\) blob \(.*\)$/\1 \2/p' |
 			( ret=0; while read mode id name; do
+				echo "Restoring file ${name#$_git_relpath}"
 				# TODO: Use git-update-index --index-info when we
 				# will depend on git new enough. --pasky
 				if ! git-update-index --add --cacheinfo "$mode" "$id" "$name"; then
-					echo "Error: Cannot mark $file for update" >&2
+					echo "Error: Cannot mark ${file#$_git_relpath} for update" >&2
 					ret=1
 					continue
 				fi
@@ -104,6 +105,7 @@ if [ "$ARGS" ]; then
 	elif [ "$objtype" = "blob" ]; then
 		[ "${#files[@]}" -gt 1 ] && echo "Warning: Restoring multiple files to a single blob" >&2
 		for file in "${files[@]}"; do
+			echo "Restoring file ${file#$_git_relpath}"
 			echo "Warning: File ${file#$_git_relpath} likely will not have correct permissions" >&2
 			git-cat-file blob "$objid" >"$file"
 			git-update-index -- "$file" || ret=1
@@ -114,8 +116,7 @@ else # no arguments - much weaker
 	[ "$objid" ] && die "you need to pass an explicit list of files to -r"
 	[ "$_git_relpath" ] && die "cannot restore files en masse in subdirectories yet"
 	if [ "$(git-ls-files --deleted)" ]; then
-		echo "Recovering files:"
-		git-ls-files --deleted | sed "s/^/$(echo -e "\t")/"
+		git-ls-files --deleted | sed "s/^/Restoring file /"
 	fi
 	git-checkout-index -q -a $force
 fi
