Make cg-tag create the tag objects only if you pass it -s
I changed my mind. In many cases the cryptographic signature is useless,
and so is then the tag object. So cg-tag without -s will behave as
before I introduced the tag object support and just make it reference
the commit object. With -s, cg-tag will create the tag object and always
try to sign it.

diff --git a/cg-tag b/cg-tag
--- a/cg-tag
+++ b/cg-tag
@@ -6,9 +6,8 @@
 # Creates a tag referencing the given commit (or 'HEAD'). You can then
 # use the tag anywhere you specify a commit or tree ID.
 #
-# cg-tag will automatically try to sign the tag, provided that you have
-# gpg installed and secret keys in your keyring. You can override the
-# default key choice by passing it the -k argument.
+# cg-tag will try to sign the tag if you give it the -s option.
+# You can override the default key choice by passing it the -k argument.
 #
 # Takes the tag name and optionally the associated ID as arguments.
 #
@@ -16,14 +15,19 @@
 # -------
 # -k KEYNAME::
 #	Use the given key to sign the tag, instead of the default one.
+# -s::
+#	Sign the tag by your private key using GPG.
 
-USAGE="cg-tag [-k KEYNAME] TAG_NAME [COMMIT_ID]"
+USAGE="cg-tag [-s [-k KEYNAME]] TAG_NAME [COMMIT_ID]"
 
 . ${COGITO_LIB}cg-Xlib
 
+sign=
 keyname=
 while optparse; do
-	if optparse -k=; then
+	if optparse -s; then
+		sign=1
+	elif optparse -k=; then
 		keyname="--default-key \"$OPTARG\""
 	else
 		optfail
@@ -45,23 +49,25 @@ mkdir -p $_git/refs/tags
 [ "$id" ] || id=$(cat $_git/HEAD)
 
 
-tagdir="$(mktemp -d -t gittag.XXXXXX)"
+if [ "$sign" ]; then
+	tagdir="$(mktemp -d -t gittag.XXXXXX)"
 
-cat <<SIGEND >"$tagdir/tag"
+	cat <<SIGEND >"$tagdir/tag"
 object $id
 type commit
 tag $name
 SIGEND
-if which gpg >/dev/null 2>&1 && [ "$(gpg --list-secret-keys)" ]; then
 	if ! gpg $keyname -bsa "$tagdir/tag"; then
 		rm -rf "$tagdir"
 		die "error signing the tag"
 	fi
 	cat "$tagdir/tag.asc" >>"$tagdir/tag"
-fi
-if ! git-mktag <"$tagdir/tag" >$_git/refs/tags/$name; then
-	rm -rf "$tagdir"
-	die "error creating tag"
-fi
+	if ! git-mktag <"$tagdir/tag" >$_git/refs/tags/$name; then
+		rm -rf "$tagdir"
+		die "error creating tag"
+	fi
 
-rm -rf "$tagdir"
+	rm -rf "$tagdir"
+else
+	echo "$id" >$_git/refs/tags/$name
+fi
