[PATCH 1/6] Add infrastructure for option parsing to cg-Xlib
Adds a new function, optparse, that handles combined options
just like optget (cg-log -cf, for example).

When called without any argument, it returns 0 if there is any
option to parse.

When called as "optparse -f" or "optparse --foo" it returns 0
if the current option in $ARGS (at $ARGPOS) matches.

When called as "optparse -f= or "optparse --foo=" it requires
an argument.

For long options, it takes an optional second argument, specifying
the number of characters in the option name that has to be present
(defaults to 1). So "optparse --foo 2" will match "--fo", but not
"--f".

Just as with optget, options can be given after arguments as
well, as in "cg-log Documentation -rorigin". Option parsing
stops after "--".

optparse leaves unparsed arguments in the $ARGS array.

Signed-off-by: Dan Holmsand <holmsand@gmail.com>

Tidyups.

Make cg-log and cg-diff use the new optparse stuff.

Signed-off-by: Petr Baudis <pasky@ucw.cz>

diff --git a/cg-Xlib b/cg-Xlib
--- a/cg-Xlib
+++ b/cg-Xlib
@@ -140,10 +140,72 @@ print_help () {
 }
 
 for option in "$@"; do
+	[ "$option" = -- ] && break
 	if [ "$option" = "-h" -o "$option" = "--help" ]; then
 		print_help ${_cg_cmd##cg-}
 	fi
 done
+
+
+ARGS=("$@")
+ARGPOS=0
+
+optshift() {
+	unset ARGS[$ARGPOS]
+	ARGS=("${ARGS[@]}")
+	[ -z "$1" -o -n "${ARGS[$ARGPOS]}" ] ||
+		die "option \`$1' requires an argument"
+}
+
+optfail() {
+	die "unrecognized option \`${ARGS[$ARGPOS]}'"
+}
+
+optconflict() {
+	die "conflicting option \`$CUROPT'"
+}
+
+optparse() {
+	unset OPTARG
+	if [ -z "$1" ]; then
+		case ${ARGS[$ARGPOS]} in
+		--)	optshift; return 1 ;;
+		-*)	return 0 ;;
+		*)	while (( ++ARGPOS < ${#ARGS[@]} )); do
+				[[ "${ARGS[$ARGPOS]}" == -- ]] && return 1
+				[[ "${ARGS[$ARGPOS]}" == -* ]] && return 0
+			done;
+			return 1 ;;
+		esac
+	fi
+
+	CUROPT=${ARGS[$ARGPOS]}
+	local match=${1%=} minmatch=${2:-1} opt=$CUROPT o=$CUROPT val
+	[[ "$1" == *= ]] && val=$match
+	case $match in
+	--*)
+		[ "$val" ] && o=${o%%=*}
+		[ ${#o} -ge $((2 + $minmatch)) -a \
+			"${match:0:${#o}}" = "$o" ] || return 1
+		[[ -n "$val" && "$opt" == *=?* ]] \
+			&& ARGS[$ARGPOS]=${opt#*=} \
+			|| optshift $val ;;
+	-?)
+		[[ "$o" == $match* ]] || return 1
+		[[ "$o" != -?-* || -n "$val" ]] || optfail
+		ARGS[$ARGPOS]=${o#$match}
+		[ "${ARGS[$ARGPOS]}" ] \
+			&& { [ "$val" ] || ARGS[$ARGPOS]=-${ARGS[$ARGPOS]}; } \
+			|| optshift $val ;;
+	*)
+		die "optparse cannot handle $1" ;;
+	esac
+
+	if [ "$val" ]; then
+		OPTARG=${ARGS[$ARGPOS]}
+		optshift
+	fi
+}
 
 
 # Check if we have something to work on, unless the script can do w/o it.
