Clean up and generalize the commit editor
The generic commit editor stuff was moved from cg-commit to cg-Xlib,
which cleaned up cg-commit code somewhat and will enable us to reuse
it in cg-tag's future tag editor.

diff --git a/cg-Xlib b/cg-Xlib
--- a/cg-Xlib
+++ b/cg-Xlib
@@ -349,6 +349,84 @@ list_untracked_files()
 
 #######################################################################
 #
+# Common message editor tools                                      {{{1
+#
+
+editor_comment_start()
+{
+	if [ -e "$_git/$1-template" ]; then
+		cat "$_git/$1-template" >>"$LOGMSG"
+	else
+		cat >>"$LOGMSG" <<EOT
+CG: -----------------------------------------------------------------------
+CG: Lines beginning with the CG: prefix are removed automatically.
+EOT
+	fi
+}
+
+# editor_comment_end [-f] ACTIONNAME
+editor_comment_end()
+{
+	local force= actionname=
+	if [ "$1" = "-f" ]; then
+		force=1; shift
+	fi
+	actionname="$1"; shift
+	[ "$force" ] || echo "CG: Do not save this file and just quit if you want to abort the $actionname." >>"$LOGMSG"
+	echo "CG: -----------------------------------------------------------------------" >>"$LOGMSG"
+}
+
+editor_msg_end()
+{
+	echo "CG: vim: textwidth=75$*" >>"$LOGMSG"
+}
+
+editor_parse_setif()
+{
+	if ! grep -q "^CG: $2:" "$LOGMSG2"; then
+		unset $1
+	else
+		export $1="$(grep "^CG: $2:" "$LOGMSG2" | cut -d ' ' -f 3-)"
+	fi
+}
+
+editor_parse_clean()
+{
+	grep -v ^CG: "$LOGMSG2" | git-stripspace >"$LOGMSG"
+}
+
+# editor [-f] ACTIONNAME ACTIONKEY
+# W/o -f asks what-to-do if user didn't modify the log message.
+# Returns $?:
+# 0	all went fine, new log message saved in $LOGMSG2
+# 1	aborted by user
+editor()
+{
+	local force= actionname= actionkey=
+	if [ "$1" = "-f" ]; then
+		force=1; shift
+	fi
+	actionname="$1"; shift
+	actionkey="$1"; shift
+
+	${EDITOR:-vi} "$LOGMSG2"
+	[ "$force" ] && return 0
+	[ "$LOGMSG2" -nt "$LOGMSG" ] && return 0
+
+	echo "Log message unchanged or not specified" >&2
+	while true; do
+		read -p "Abort or $actionname? [a$actionkey] " choice
+		if [ "$choice" = "a" ] || [ "$choice" = "q" ]; then
+			return 1
+		elif [ "$choice" = "$actionkey" ]; then
+			return 0
+		fi
+	done
+}
+
+
+#######################################################################
+#
 # Misc. common Git operations wrappers                             {{{1
 #
 
diff --git a/cg-commit b/cg-commit
--- a/cg-commit
+++ b/cg-commit
@@ -222,7 +222,7 @@ while optparse; do
 		forceeditor=1
 	elif optparse -E; then
 		forceeditor=1
-		commitalways=1
+		commitalways=-f
 	elif optparse -f; then
 		force=1
 	elif optparse -q; then
@@ -362,14 +362,9 @@ if [ "$signoff" ] && ! grep -q -i "signed-off-by: $signoff" $LOGMSG; then
 	echo "Signed-off-by: $signoff"
 fi >> $LOGMSG
 
-if [ -e "$_git/commit-template" ]; then
-	cat "$_git/commit-template" >>"$LOGMSG"
-else
-	cat >>"$LOGMSG" <<EOT
-CG: -----------------------------------------------------------------------
-CG: Lines beginning with the CG: prefix are removed automatically.
-EOT
-fi
+# CG: -----------------------------------------------------------------------
+editor_comment_start commit
+
 if [ "$GIT_AUTHOR_NAME" -o "$GIT_AUTHOR_EMAIL" -o "$GIT_AUTHOR_DATE" ]; then
 	echo "CG:" >>"$LOGMSG"
 	[ "$GIT_AUTHOR_NAME" ] && echo "CG: Author: $GIT_AUTHOR_NAME" >>"$LOGMSG"
@@ -407,9 +402,11 @@ if [ "$review" ]; then
 	git-apply --stat --summary < "$PATCH" | sed 's/^/CG: /'
 	echo "CG:"
 fi >>"$LOGMSG"
-[ "$commitalways" ] || echo "CG: Do not save this file and just quit if you want to abort the commit." >>"$LOGMSG"
-echo "CG: -----------------------------------------------------------------------" >>"$LOGMSG"
 
+# CG: -----------------------------------------------------------------------
+editor_comment_end $commitalways commit
+
+ftdiff=
 if [ "$review" ]; then
 	{
 		echo "CG:"
@@ -420,37 +417,25 @@ if [ "$review" ]; then
 		cat "$PATCH"
 	} >>"$LOGMSG"
 
-	ftdiff="filetype=diff"
+	ftdiff=" filetype=diff"
 fi
-
-echo "CG: vim: textwidth=75 $ftdiff" >>"$LOGMSG"
+editor_msg_end $ftdiff
 
 cp "$LOGMSG" "$LOGMSG2"
 if tty -s; then
-	if [ "$editor" ]; then
-		${EDITOR:-vi} "$LOGMSG2"
-		if ! [ "$commitalways" ] && ! [ "$LOGMSG2" -nt "$LOGMSG" ]; then
-			echo "Log message unchanged or not specified" >&2
-			while true; do
-				read -p 'Abort or commit? [ac] ' choice
-				if [ "$choice" = "a" ] || [ "$choice" = "q" ]; then
-					rm "$LOGMSG" "$LOGMSG2"
-					[ "$review" ] && rm "$PATCH" "$PATCH2"
-					echo "Commit message not modified, commit aborted" >&2
-					if [ "$merging" ]; then
-						cat >&2 <<__END__
+	if [ "$editor" ] && ! editor $commitalways commit c; then
+		rm "$LOGMSG" "$LOGMSG2"
+		[ "$review" ] && rm "$PATCH" "$PATCH2"
+		echo "Commit message not modified, commit aborted" >&2
+		if [ "$merging" ]; then
+			cat >&2 <<__END__
 Note that the merge is NOT aborted - you can cg-commit again, cg-reset will abort it.
 __END__
-						[ -s "$_git/commit-ignore" ] && cat >&2 <<__END__
+			[ -s "$_git/commit-ignore" ] && cat >&2 <<__END__
 (But note that cg-reset will remove your pending local changes as well!)
 __END__
-					fi
-					exit 1
-				elif [ "$choice" = "c" ]; then
-					break
-				fi
-			done
 		fi
+		exit 1
 	fi
 	if [ ! "$ignorecache" ] && [ ! "$merging" ] && [ ! "$review" ]; then
 		eval "newcommitfiles=($(grep ^CG:F "$LOGMSG2" | sed 's/^CG:F *\(.*\)$/"\1"/'))"
@@ -463,25 +448,18 @@ __END__
 			customfiles=1
 		fi
 	fi
-	setif () {
-		if ! grep -q "^CG: $2:" "$LOGMSG2"; then
-			unset $1
-		else
-			export $1="$(grep "^CG: $2:" "$LOGMSG2" | cut -d ' ' -f 3-)"
-		fi
-	}
-	setif GIT_AUTHOR_NAME Author
-	setif GIT_AUTHOR_EMAIL Email
-	setif GIT_AUTHOR_DATE Date
+	editor_parse_setif GIT_AUTHOR_NAME Author
+	editor_parse_setif GIT_AUTHOR_EMAIL Email
+	editor_parse_setif GIT_AUTHOR_DATE Date
 else
 	cat >>"$LOGMSG2"
 fi
 
-# Remove heading and trailing blank lines.
 if [ ! "$review" ]; then
-	grep -v ^CG: "$LOGMSG2" | git-stripspace >"$LOGMSG"
+	editor_parse_clean
 else
-	sed '/^CG: Changes summary:/,$d' < "$LOGMSG2" | grep -v ^CG: | git-stripspace >"$LOGMSG"
+	sed '/^CG: Changes summary:/,$d' < "$LOGMSG2" > "$LOGMSG"
+	mv "$LOGMSG" "$LOGMSG2"; editor_parse_clean
 	sed -n '/^CG: Changes summary:/,$p' < "$LOGMSG2" | grep -v ^CG: > "$PATCH2"
 fi
 rm "$LOGMSG2"
