Portable stub for the stat call
cg-pull calls stat -c '%s' file, which is now stubbed in cg-Xlib and
emulated if there's no stat on the system.

diff --git a/cg-Xlib b/cg-Xlib
--- a/cg-Xlib
+++ b/cg-Xlib
@@ -45,6 +45,20 @@ mktemp () {
 	$(which mktemp) $dirarg $prefix"$1"
 }
 
+stat () {
+	if [ "$1" != "-c" ] || [ "$2" != "%s" ]; then
+		echo "INTERNAL ERROR: Unsupported stat call $@" >&2
+		return 1
+	fi
+	if [ "$HAVE_STAT" ]; then
+		$(which stat) "$@"
+		return
+	fi
+
+	# It's always -c '%s' now.
+	ls -l "$3" | awk '{ print $5 }'
+}
+
 showdate () {
 	date="$1"
 	format="$2"
@@ -169,4 +183,6 @@ fi
 
 export BROKEN_MKTEMP=1
 del=$($(which mktemp) -t 2>/dev/null) && { rm $del; export BROKEN_MKTEMP=; }
+export HAVE_STAT=
+which stat >/dev/null 2>&1 && export HAVE_STAT=1
 has_gnudate=$(date -Rud "1970-01-01 UTC" 2>/dev/null)
