Speed up the *-id helpers
cg-Xnormid now can also output type of the hash it carries, saving
frequently one git-cat-file -t call for the *-id helpers. Should speed
them up a bit.

diff --git a/commit-id b/commit-id
--- a/commit-id
+++ b/commit-id
@@ -9,9 +9,11 @@
 
 id="$1"
 normid=$(. ${COGITO_LIB}cg-Xnormid "$id") || exit 1
+type=${normid#* }; [ "$type" ] || type=$(git-cat-file -t "$normid")
+normid=${normid% *}
 
-if [ "$(git-cat-file -t "$normid")" != "commit" ]; then
-	echo "Invalid commit id: $id" >&2
+if [ "$type" != "commit" ]; then
+	echo "Invalid commit id: $normid" >&2
 	exit 1
 fi
 
diff --git a/tree-id b/tree-id
--- a/tree-id
+++ b/tree-id
@@ -7,7 +7,8 @@
 
 id="$1"
 normid=$(. ${COGITO_LIB}cg-Xnormid "$id") || exit 1
-type=$(git-cat-file -t "$normid")
+type=${normid#* }; [ "$type" ] || type=$(git-cat-file -t "$normid")
+normid=${normid% *}
 
 if [ "$type" = "commit" ]; then
 	normid=$(git-cat-file commit "$normid" | sed -e 's/tree //;q')
@@ -15,7 +16,7 @@ if [ "$type" = "commit" ]; then
 fi
 
 if [ "$type" != "tree" ]; then
-	echo "Invalid tree id: $id" >&2
+	echo "Invalid tree id: $normid" >&2
 	exit 1
 fi
 
