Kill gitXnormid.sh and split its functionality to before-just-dumb-wrappers commit-id and tree-id.

diff --git a/commit-id b/commit-id
--- a/commit-id
+++ b/commit-id
@@ -5,4 +5,36 @@
 #
 # Takes the appropriate ID, defaults to HEAD.
 
-gitXnormid.sh -c $1
+SHA1="[A-Za-z0-9]{40}"
+SHA1ONLY="^$SHA1$"
+
+id=$1
+if [ ! "$id" ] || [ "$id" = "this" ] || [ "$id" = "HEAD" ]; then
+	id=$(cat .git/HEAD)
+fi
+
+if (echo $id | egrep -vq "$SHA1ONLY") && [ -r ".git/tags/$id" ]; then
+	id=$(cat ".git/tags/$id")
+fi
+
+if (echo $id | egrep -vq "$SHA1ONLY") && [ -r ".git/heads/$id" ]; then
+	id=$(cat ".git/heads/$id")
+fi
+
+idpref=$(echo "$id" | cut -c -2)
+idpost=$(echo "$id" | cut -c 3-)
+if [ $(find ".git/objects/$idpref" -name "$idpost*" 2>/dev/null | wc -l) -eq 1 ]; then
+	id=$idpref$(basename $(echo .git/objects/$idpref/$idpost*))
+fi
+
+if echo $id | egrep -vq "$SHA1ONLY"; then
+	echo "Invalid id: $id" >&2
+	exit 1
+fi
+
+if [ "$(cat-file -t "$id")" != "commit" ]; then
+	echo "Invalid id: $id" >&2
+	exit 1
+fi
+
+echo $id
diff --git a/tree-id b/tree-id
--- a/tree-id
+++ b/tree-id
@@ -5,4 +5,14 @@
 #
 # Takes ID of the appropriate commit, defaults to HEAD.
 
-gitXnormid.sh $1
+SHA1="[A-Za-z0-9]{40}"
+TREE="^tree $SHA1$"
+
+id=$(cat-file commit $(commit-id "$1") | egrep "$TREE" | cut -d ' ' -f 2)
+
+if [ "$(cat-file -t "$id")" != "tree" ]; then
+	echo "Invalid id: $id" >&2
+	exit 1
+fi
+
+echo $id
