Make git-merge-one-file-script cleanup its temporary files properly. Also even file with conflicts is written over the original one.

diff --git a/git-merge-one-file-script b/git-merge-one-file-script
--- a/git-merge-one-file-script
+++ b/git-merge-one-file-script
@@ -45,8 +45,17 @@ case "${1:-.}${2:-.}${3:-.}" in
 	orig=$(unpack-file $1)
 	src1=$(unpack-file $2)
 	src2=$(unpack-file $3)
-	merge "$src2" "$orig" "$src1" || (echo Leaving conflict merge in $src2 && exit 1)
-	(cp "$src2" "$4" && update-cache --add -- "$4") || (echo "Choosing $src2 -> $4 failed" && exit 1)
+	ret=0
+	if ! merge "$src2" "$orig" "$src1"; then
+		echo Conflicting merge!
+		cp "$src2" "$4"
+		ret=1
+
+	elif ! cp "$src2" "$4" && update-cache --add -- "$4"; then
+		echo "Choosing $src2 -> $4 failed"
+		ret=1
+	fi
+	rm -- "$orig" "$src1" "$src2"
 	exit 0
 	;;
 
